### Obtener todos los autores
GET http://localhost:3000/api/autores

###

### Obtener autor por ID 
GET http://localhost:3000/api/autores/1

###

### Crear autor
POST http://localhost:3000/api/autores
Content-Type: application/json

{
    "nombre": "Pablo",
    "email": "pablo@prueba.com",
    "imagen": "https://prueba.com/pablo.jpg"
}

###

### Actualizar autor
PUT http://localhost:3000/api/autores/1
Content-Type: application/json

{
    "nombre": "Ana López Editado",
    "email": "ana.edited@example.com",
    "imagen": "https://example.com/anaupdate.jpg"
}

###

### Eliminar autor
DELETE http://localhost:3000/api/autores/1

###

### Obtener todos los posts
GET http://localhost:3000/api/posts

###

### Obtener post por ID
GET http://localhost:3000/api/posts/2

###

### Obtener posts por autor
GET http://localhost:3000/api/posts/autor/5

###

### Crear post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "titulo": "Post de Pablo",
    "descripcion": "Este es el post de prueba de Pablo",
    "categoria": "Deporte",
    "autor_id": 5
}

###

### Actualizar post
PUT http://localhost:3000/api/posts/1
Content-Type: application/json

{
    "titulo": "Título editado",
    "descripcion": "Contenido editado del post",
    "categoria": "Actualidad",
    "autor_id": 1
}

###

### Eliminar post
DELETE http://localhost:3000/api/posts/1
